[pytest]
testpaths = .
addopts = -q --html=report.html --self-contained-html -n auto
python_files = test_*.py *_test.py
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
